// Market-specific blog articles that are published in Swedish only (byggdagbok,
// ROT, ÄTA, ID06, egenkontroll/KMA, AB 04 / AMA AF, lead-magnet templates …).
// For these slugs the article page must NOT emit en/ru hreflang alternates,
// since those locale URLs don't exist and would be hreflang-to-404.
//
// Add a slug here when you publish an sv-only article in the CMS.
export const SV_ONLY_ARTICLE_SLUGS = new Set<string>([
  'anlita-underentreprenor',
  'a-conto-fakturering-bygg',
  'entreprenorsansvar-lon',
  'fast-pris-eller-lopande-rakning',
  'tackningsbidrag-byggforetag',
  'reklamation-hantverkstjanst-frister',
  'kontrollansvarig-nar-behovs',
  'byggmotesprotokoll-mall',
  'overlamning-relationshandlingar',
  'kvartsdamm-regler-bygg',
  'byggdagbok',
  'egenkontroll',
  'ata-arbeten',
  'personalliggare',
  'rot-avdrag',
  'id06',
  'bemanning-och-personalplanering',
  'ab-04-och-abt-06',
  'arbetsmiljoplan',
  'attestering',
  'franvaro-i-byggforetag',
  'heta-arbeten',
  'slutbesiktning',
  'timpris-hantverkare',
  'skriva-offert',
  'moms-hantverkare',
  'tidrapportering',
  'fakturera-som-hantverkare',
  'rakna-material-till-bygget',
  'paslag-pa-material',
  'nya-vatrumsregler-2026',
  'e-faktura-obligatorisk-byggforetag',
  'berakna-u-varde-isolering',
  'kunden-betalar-inte-fakturan',
  'mangdforteckning-bygg',
  'muntligt-avtal-sakra-bevis',
  'arbetsmiljoansvar-egenforetagare',
  'betalningsvillkor-faktura-bygg',
  'kontrollavgift-personalliggare',
  'bas-p-bas-u',
  'garantitid-ansvarstid-ab-04',
  'abs-18-hantverkarformularet-17',
  'vad-kostar-en-anstalld-byggforetag',
  'likviditet-byggforetag',
  'anstalla-personal-byggforetag',
  'enskild-firma-eller-aktiebolag-bygg',
]);

export function isSvOnlyArticle(slug: string): boolean {
  return SV_ONLY_ARTICLE_SLUGS.has(slug);
}
